name: Eggs Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        deno-version: [1.2.0]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno run --unstable -A eggs/mod.ts link --key ${{ secrets.NESTAPIKEY }}
        # TODO(eggs@0.2.0): remove --key
      - run: deno test --unstable -A eggs/tests/commands