name: Eggs Test on Deno Nightly

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno Nightly (windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          iwr https://deno-nightly.now.sh/install.ps1 -useb | iex
          echo "::set-env name=DENO_INSTALL::${DENO_INSTALL:-$HOME/.deno}"
          echo "::add-path::$HOME/.deno/bin"
        
      - name: Setup Deno Nightly (mac & linux)
        if: startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu')
        run: |
          curl -fsSL https://deno-nightly.now.sh/install.sh | sh
          echo "::set-env name=DENO_INSTALL::${DENO_INSTALL:-$HOME/.deno}"
          echo "::add-path::$HOME/.deno/bin"

      - name: Deno test
        run: deno-nightly test -A --unstable
