name: Ship

on:
  push:
    branches: [master]


jobs:
  release:
    runs-on: ubuntu-latest

    env:
      NESTAPIKEY: ${{ secrets.NESTAPIKEY }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2

      - name: Setup Drake
        run: deno run -A Drakefile.ts setup-github-actions

      - name: Get eggs version
        run: drake get-version

      - name: Draft release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-template.yml
          version: ${{ env.EGGS_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish eggs
        run: drake ship
